apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-cd-pipeline-run
spec:
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc
  params:
    - name: app-name
      value: cicd-app
    - name: build-image
      value: image-registry.openshift-image-registry.svc:5000/YOUR_NAMESPACE/cicd-app
