apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: app-name
      type: string
    - name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
      runAfter: [cleanup]
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: https://github.com/YOUR_USERNAME/YOUR_REPO.git
        - name: revision
          value: main

    - name: flake8
      taskRef:
        name: flake8
      runAfter: [git-clone]
      workspaces:
        - name: source
          workspace: output

    - name: nose
      taskRef:
        name: nose
      runAfter: [flake8]
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      taskRef:
        name: buildah
      runAfter: [nose]
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: $(params.build-image)

  finally:
    - name: deploy
      taskRef:
        name: openshift-client
      workspaces:
        - name: source
          workspace: output
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
